active_tab_background   #ffffff   
active_tab_foreground   #111111   
background              #1d1d20   
color0                  #191919   
color1                  #dddddd   
color10                 #cccccc   
color11                 #aaaaaa   
color12                 #a7a7a7   
color13                 #dddddd   
color14                 #cccccc   
color2                  #cccccc   
color3                  #aaaaaa   
color4                  #a7a7a7   
color5                  #dddddd   
color6                  #cccccc   
color7                  #828282   
color8                  #3c3c3c   
color9                  #dddddd   
cursor                  #ffffff   
cursor_trail_color      #ffffff   
foreground              #ffffff   
inactive_border_color   #191919   
inactive_tab_background #191919   
inactive_tab_foreground #ffffff   
selection_background    #828282   
selection_foreground    #ffffff   
url_color               #ffffff
window_padding_width 10
cursor_trail 5
cursor_trail_decay 0.1 0.5
cursor_shape underline
shell_integration no-cursor
